# for a description of available keys, see https://github.com/typst/packages/?tab=readme-ov-file#package-format

[package]
name = "my-package"
version = "0.0.1"
entrypoint = "src/lib.typ"
authors = [
  "Clemens Koza <https://github.com/SillyFreak/>"
]
license = "MIT"
description = "my package"
# homepage = ""
repository = "https://github.com/SillyFreak/typst-my-package"
keywords = []
categories = []
disciplines = []
compiler = ""
exclude = [
	".github",
	"docs",
	"gallery",
	"scripts",
	"tests",
	".typstignore",
	"Justfile",
]

# [template]
# path = "template"
# entrypoint = "main.typ"
# thumbnail = "thumbnail.png"

# [tool.mytool]
# foo = "bar"
